SuperHeroesApp/Models/Appearance.cs
using Newtonsoft.Json;

namespace SuperHeroesApp.Models
{
    public class Appearance
    {
        public string gender { get; set; }
        public string race { get; set; }
        public List<string> height { get; set; }
        public List<string> weight { get; set; }

        [JsonProperty("eye-color")]
        public string EyeColor { get; set; }

        [JsonProperty("hair-color")]
        public string HairColor { get; set; }
    }
}

SuperHeroesApp/Models/Biography.cs
using Newtonsoft.Json;

namespace SuperHeroesApp.Models
{
    public class Biography
    {
        [JsonProperty("full-name")]
        public string FullName { get; set; }

        [JsonProperty("alter-egos")]
        public string AlterEgos { get; set; }
        public List<string> aliases { get; set; }

        [JsonProperty("place-of-birth")]
        public string PlaceOfBirth { get; set; }

        [JsonProperty("first-appearance")]
        public string FirstAppearance { get; set; }
        public string publisher { get; set; }
        public string alignment { get; set; }
    }
}

SuperHeroesApp/Models/Connections.cs
using Newtonsoft.Json;

namespace SuperHeroesApp.Models
{
    public class Connections
    {
        [JsonProperty("group-affiliation")]
        public string GroupAffiliation { get; set; }
        public string relatives { get; set; }
    }
}

SuperHeroesApp/Models/ErrorViewModel.cs
namespace SuperHeroesApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperHeroesApp/Models/Image.cs
namespace SuperHeroesApp.Models
{
    public class Image
    {
        public string url { get; set; }
    }
}

SuperHeroesApp/Models/Powerstats.cs
namespace SuperHeroesApp.Models
{
    public class Powerstats
    {
        public string intelligence { get; set; }
        public string strength { get; set; }
        public string speed { get; set; }
        public string durability { get; set; }
        public string power { get; set; }
        public string combat { get; set; }
    }
}

SuperHeroesApp/Models/Result.cs
namespace SuperHeroesApp.Models
{
    public class Result
    {
        public string id { get; set; }
        public string name { get; set; }
        public Powerstats powerstats { get; set; }
        public Biography biography { get; set; }
        public Appearance appearance { get; set; }
        public Work work { get; set; }
        public Connections connections { get; set; }
        public Image image { get; set; }
    }
}

SuperHeroesApp/Models/SuperHeroeModel.cs
using Newtonsoft.Json;

namespace SuperHeroesApp.Models
{
    public class SuperHeroeModel
    {
        public string response { get; set; }
        public string id { get; set; }
        public string name { get; set; }
        public Powerstats powerstats { get; set; }
        public Biography biography { get; set; }
        public Appearance appearance { get; set; }
        public Work work { get; set; }
        public Connections connections { get; set; }
        public Image image { get; set; }
    }

    public class SuperHeroeSearchModel 
    {
        public string response { get; set; }
        public string error { get; set; }

        [JsonProperty("results-for")]
        public string ResultsFor { get; set; }
        public List<Result> results { get; set; }
    }
}

SuperHeroesApp/Models/Work.cs
namespace SuperHeroesApp.Models
{
    public class Work
    {
        public string occupation { get; set; }
        public string @base { get; set; }
    }
}

SuperHeroesApp/Controllers/CharacterController.cs
using Microsoft.AspNetCore.Mvc;
using SuperHeroesApp.Models;

namespace SuperHeroesApp.Controllers
{
    public class CharacterController : Controller
    {
        private ISuperHeroeClient _client;

        public CharacterController(ISuperHeroeClient client)
        {
            _client = client;
        }

        public IActionResult Index(string Id)
        {
            var resultados = _client.SuperHeroeDetails(Id);

            if (resultados.response.Contains("error"))
            {
                Response.StatusCode = 404;
                return Redirect("~/Error/404");
            }

            return View(resultados);
        }
    }
}

SuperHeroesApp/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace SuperHeroesApp.Controllers
{
    public class ErrorController : Controller
    {

        [Route("Error/{statusCode}")]
        public IActionResult HttpStatusResponse(int statusCode)
        {
            return View("NotFound");
        }
    }
}

SuperHeroesApp/Controllers/SuperHeroesController.cs
using Microsoft.AspNetCore.Mvc;
using SuperHeroesApp.Models;

namespace SuperHeroesApp.Controllers
{
    public class SuperHeroesController : Controller
    {
        private ISuperHeroeClient _client;

        public SuperHeroesController(ISuperHeroeClient client)
        {
            _client = client;
        }

        public IActionResult Index()
        {
            return View(new SuperHeroeSearchModel());
        }

        [HttpGet]
        public IActionResult Search(SuperHeroeSearchModel model)
        {
            var resultados = _client.SearchSuperHeroe(model.ResultsFor);

            if (resultados.response.Contains("error"))
                TempData["msg"] = resultados.error;

            return View("Index", resultados);
        }
    }
}

SuperHeroesApp/Views/Character/Index.cshtml
@model SuperHeroesApp.Models.SuperHeroeModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row m-b-lg m-t-lg">
        <div class="col-md-6">
            <div class="profile-image">
                <img src="@Model.image.url" class="rounded-circle circle-border m-b-md" />
            </div>
            <div class="profile-info">
                <div>
                    <h2>@Model.name</h2>
                    <h4>@Model.biography.FullName</h4>
                    <small>@Model.biography.PlaceOfBirth</small>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <table class="table small m-b-xs">
                <tbody>
                    <tr>
                        <td>
                            <strong>Intelligence</strong>
                            @Model.powerstats.intelligence
                        </td>
                        <td>
                            <strong>strength</strong>
                            @Model.powerstats.strength
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Speed</strong>
                            @Model.powerstats.speed
                        </td>
                        <td>
                            <strong>Durability</strong>
                            @Model.powerstats.durability
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Power</strong>
                            @Model.powerstats.power
                        </td>
                        <td>
                            <strong>Combat</strong>
                            @Model.powerstats.combat
                        </td>
                    </tr>
                    <tr>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="ibox">
                <div class="ibox-content">
                    <h3>About @Model.biography.FullName</h3>
                    <div class="hr-line-dashed"></div>
                    <p class="small">
                        <strong>Alter Ego:</strong> @Model.biography.AlterEgos
                    </p>
                    <p class="small">
                        <strong>First Appearance:</strong> @Model.biography.FirstAppearance
                    </p>
                    <p class="small">
                        <strong>Publisher:</strong> @Model.biography.publisher
                    </p>
                    <p class="small">
                        <strong>Aligment:</strong> @Model.biography.alignment
                    </p>
                    <p class="small">
                        <strong>Aliases:</strong>
                        @String.Join(", ",@Model.biography.aliases)
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="ibox">
                <div class="ibox-content">
                    <h3>Work and Connections </h3>
                    <div class="hr-line-dashed"></div>
                    <p class="small">
                        <strong>Occupation:</strong> @Model.work.occupation
                    </p>
                    <p class="small">
                        <strong>Base:</strong> @Model.work.@@base
                    </p>
                    <p class="small">
                        <strong>Group Affiliation:</strong> @Model.connections.GroupAffiliation
                    </p>
                    <p class="small">
                        <strong>Relatives:</strong> @Model.connections.relatives
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="ibox">
                <div class="ibox-content">
                    <h3>Appearance </h3>
                    <div class="hr-line-dashed"></div>
                    <p class="small">
                        <strong>Gender:</strong> @Model.appearance.gender
                    </p>
                    <p class="small">
                        <strong>Race:</strong> @Model.appearance.race
                    </p>
                    <p class="small">
                        <strong>Eye Color:</strong> @Model.appearance.EyeColor
                    </p>
                    <p class="small">
                        <strong>Hair Color:</strong> @Model.appearance.HairColor
                    </p>
                    <p class="small">
                        <strong>Height:</strong> @String.Join(" - ", @Model.appearance.height)
                    </p>
                    <p class="small">
                        <strong>Weight:</strong> @String.Join(" - ", @Model.appearance.weight)
                    </p>
                </div>
            </div>
        </div>

    </div>
</div>

SuperHeroesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SuperHeroesApp</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/toastr.css" />
    <link rel="stylesheet" href="~/fonts/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/plugins/dataTables/datatables.min.css" />
</head>
<body>
    <div id="wrapper">
        <div id="page-wrapper" class="gray-bg">
            <div class="wrapper wrapper-content">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/js/jquery-3.5.0.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/inspinia.js"></script>
    <script src="~/js/plugins/dataTables/datatables.min.js"></script>
    @RenderSection("Scripts", required: false)

    <script>
        $(document).ready(function () {
            @RenderSection("DocumentReady", false)
        });
    </script>

</body>
</html>

SuperHeroesApp/Views/SuperHeroes/Index.cshtml
@model SuperHeroesApp.Models.SuperHeroeSearchModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="col-lg-12" style="text-align:center">
        <h3>Search for your favorite superheroes!</h3>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-content">
                <div class="row">
                    <div class="col-sm-12">
                        <form action="@Url.Action("Search", "SuperHeroes")" method="get">
                            <div class="input-group">
                                @Html.TextBoxFor(item => item.ResultsFor, new { @class ="form-control" })
                                <span class="input-group-btn">
                                    <button id="btnGlass" class="btn btn-primary" type="submit">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <br />
                <div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="searchResults">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Gender</th>
                                    <th>Occupation</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.results != null)
                                {
                                    @foreach (var item in Model.results)
                                    {
                                        <tr>
                                            <td class="client-avatar">
                                                <img src="@item.image.url">
                                            </td>
                                            <td>@item.name</td>
                                            <td>@item.appearance.gender</td>
                                            <td>@item.work.occupation</td>
                                            <td class="client-status">
                                                <span class='btn-group'>
                                                    <a href='@Url.Action("Index","Character", new  { id = item.id})/' class='btn btn-sm btn-primary' title='Super hereoe details'>
                                                        <span class='fa fa-fw fa-search'></span>
                                                        Details
                                                    </a>
                                                </span>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
<script type="text/javascript" src="~/js/search/searchSuperHeroejs.js"></script>

}

@section documentReady{
    superHeroe.Search.ShowValidationSummary('@TempData["msg"]');
}

SuperHeroesApp/Views/SuperHeroes/_SearchResults.cshtml
@model SuperHeroesApp.Models.SuperHeroeSearchModel

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Gender</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.results)
            {
                <tr>
                    <td>@item.name</td>
                    <td>@item.appearance.gender</td>
                </tr>
            }
        </tbody>
    </table>
</div>